platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SimpleNetworkLayer' do
    
  use_frameworks!

  target 'SimpleNetworkLayerTests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 6.0.0'
    pod 'OHHTTPStubs/Swift', '~> 6.0.0'
  end

end
